CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(20) NOT NULL,
	SEXO CHAR(2) NOT NULL,
	CPF VARCHAR(20) NOT NULL,
	EMAIL VARCHAR (40) NOT NULL
)
GO


CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY IDENTITY,
	PAIS VARCHAR(15) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	BAIRRO VARCHAR (20) NOT NULL,
	RUA VARCHAR (20) NOT NULL,
	NUMERO CHAR(7) NOT NULL,
	ID_CLIENTE INT 
)
GO

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	NUMERO VARCHAR(15),
	TIPO CHAR(3),
	ID_CLIENTE INT 
)
GO

CREATE TABLE CARRO (
	IDCARRO INT PRIMARY KEY IDENTITY,
	MARCA VARCHAR(20) NOT NULL,
	PLACA VARCHAR (10) NOT NULL,
	ANO CHAR(4)  NOT NULL,
	ID_CLIENTE INT 
)
GO

CREATE TABLE MOTO (
	IDMOTO	INT PRIMARY KEY IDENTITY,
	MARCA VARCHAR(15) NOT NULL,
	PLACA VARCHAR(15) NOT NULL,
	ANO CHAR (4) NOT NULL,
	ID_CLIENTE INT 
)
GO

ALTER TABLE ENDERECO ADD CONSTRAINT FK_USUARIO_ENDERECO
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
GO

ALTER TABLE TELEFONE ADD CONSTRAINT FK_USUARIO_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
GO

ALTER TABLE CARRO ADD CONSTRAINT FK_USUARIO_CARRO
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
GO

ALTER TABLE MOTO ADD CONSTRAINT FK_USUARIO_MOTO
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
GO


INSERT INTO CLIENTE VALUES('THALES HENRIQUE','M','1234567','THALES@123.COM')
INSERT INTO CLIENTE VALUES('VINICIUS AMARAL','M','9876547','VINICIUS@44.COM.BR')
INSERT INTO CLIENTE VALUES('MARIA SERGETE','F','54877952','MARIA.CA@.NET')
INSERT INTO CLIENTE VALUES('SCARLET TRINDADE','F','32659847','SCARLET.COM.@1234')
INSERT INTO CLIENTE VALUES('CARLOS VITOR','M','2144547','CARLOSVITOR@477')
GO

SELECT * FROM CLIENTE

INSERT INTO ENDERECO VALUES('BRASIL', 'MG', 'TRES PONTA', 'DAVANUZE', 'VALEROI', '099',1)
INSERT INTO ENDERECO VALUES('VENEZUELA', 'PT', 'CATELES', 'TENIEE', 'LOSIEI', '1234',2)
INSERT INTO ENDERECO VALUES('BRASIL', 'SP', 'LOPOIAU', 'DATENATAE', 'MEMENS', '0457',3)
INSERT INTO ENDERECO VALUES('BRASIL', 'MT', 'MATOES', 'MOENA', 'TERERASS', '54547',4)
INSERT INTO ENDERECO VALUES('VENEZUELA', 'PT', 'POITESR', 'RESTORIES', 'MNEUSOED', '784774',5)
INSERT INTO ENDERECO VALUES('BRASIL', 'SP', 'LOPOIAU', 'PORIESTIE', 'MEDEIROS', '1224',3)
INSERT INTO ENDERECO VALUES('BRASIL', 'PONTE PRETA', 'PADRE RIBO', 'PORTES', 'MOSANBIQ', '41147',5)
GO

SELECT * FROM ENDERECO

INSERT INTO TELEFONE VALUES ('988447711','RES',1)
INSERT INTO TELEFONE VALUES ('321147657','CEL',2)
INSERT INTO TELEFONE VALUES ('324589541','CEL',4)
INSERT INTO TELEFONE VALUES ('147587441','RES',2)
INSERT INTO TELEFONE VALUES ('321147786','CEL',1)
INSERT INTO TELEFONE VALUES ('685441177','RES',4)
INSERT INTO TELEFONE VALUES ('324569987','CEL',1)
INSERT INTO TELEFONE VALUES ('123265654','FIX',4)
INSERT INTO TELEFONE VALUES ('147758632','RES',4)
INSERT INTO TELEFONE VALUES ('653298774','FIX',5)
INSERT INTO TELEFONE VALUES ('110044775','RES',5)

SELECT * FROM TELEFONE 

INSERT INTO CARRO VALUES ('PEUGEOT','XTZH-55','2003',1)
INSERT INTO CARRO VALUES ('FIAT','POTG-56','2010',3)
INSERT INTO CARRO VALUES ('RENAULT','XTZH-57','2007',4)
INSERT INTO CARRO VALUES ('BMW','XTZH-58','2023',5)
INSERT INTO CARRO VALUES ('TESLA','XTZH-59','2025',2)

SELECT * FROM CARRO 

INSERT INTO MOTO VALUES ('HONDA','HTMB-10','2010',1)
INSERT INTO MOTO VALUES ('FAZER','HTMB-11','2012',3)
INSERT INTO MOTO VALUES ('YAMAHA','HTMB-12','2015',4)
INSERT INTO MOTO VALUES ('BMW','HTMB-13','2023',5)
INSERT INTO MOTO VALUES ('FAZER','HTMB-14','2014',2)
GO



SELECT C.IDCLIENTE, C.NOME, C.CPF, T.NUMERO, T.TIPO, E.CIDADE, E.BAIRRO, CA.MARCA AS CARRO
, CA.PLACA AS CARRO, M.MARCA AS MOTO,M. PLACA AS MOTO FROM CLIENTE C
INNER JOIN ENDERECO E 
ON E.ID_CLIENTE = C.IDCLIENTE
INNER JOIN TELEFONE T
ON T.ID_CLIENTE = C.IDCLIENTE
INNER JOIN CARRO CA
ON CA.ID_CLIENTE = C.IDCLIENTE
INNER JOIN MOTO M
ON M.ID_CLIENTE = C.IDCLIENTE
GO



/*					EXERCICIOS 

1 - MOSTRE TODOS OS NOMES E CPF DA TABELA CLIENTE 

2 - MOSTRE APENAS OS VEICULOS DA MARCA BMW 

3 - MOSTRE APENAS O ID E O NOME DAS PESSOAS QUE MORAM NO BRASIL.

4 - MOSTRE TODAS AS INFORMAÇOES DA PESSOA COM ID 5 

*/

				 --RESOLUÇOES--

/*1*/  SELECT NOME,CPF  FROM CLIENTE

/*2*/  SELECT C.IDCLIENTE, C.NOME ,CA.PLACA AS PLACACARRO, CA.MARCA AS MARCACARRO, M.MARCA AS MARCAMOTO, M.PLACA AS PLACAMOTO FROM CLIENTE C
		INNER JOIN CARRO CA
		ON CA.ID_CLIENTE = C.IDCLIENTE
		INNER JOIN MOTO M
		ON M.ID_CLIENTE = C.IDCLIENTE
		WHERE CA.MARCA = 'BMW'
		AND
		M.MARCA = 'BMW'

/*3*/  SELECT C.IDCLIENTE, C.NOME FROM CLIENTE C 
		INNER JOIN ENDERECO E
		ON E.ID_CLIENTE = C.IDCLIENTE 
		WHERE PAIS = 'BRASIL'

/*4*/  SELECT * FROM CLIENTE C
		INNER JOIN ENDERECO E
		ON E.ID_CLIENTE = C.IDCLIENTE
		INNER JOIN TELEFONE T
		ON T.ID_CLIENTE = C.IDCLIENTE
		INNER JOIN CARRO CA 
		ON CA.ID_CLIENTE = C.IDCLIENTE
		INNER JOIN MOTO M 
		ON M.ID_CLIENTE = C.IDCLIENTE
		WHERE C.IDCLIENTE = 5
        
		
		




